Repository codestates-seb/seb41_main_012, pull requests merged in 2023-01, with the labels that each got.

#5 #1 - feat : 와이어프레임 초기 세팅 중
  client/data.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/MatPickersList.tsx
  client/src/components/PostRead.tsx
  client/src/pages/Domain.tsx
  client/src/pages/MatPicker.tsx
Labels: style, FE

#12 Pages/my page
  client/.eslintrc.json
  client/fake_server/matData.json
  client/package-lock.json
  client/package.json
  client/src/components/Header.tsx
  client/src/components/HeaderFeedHide.tsx
  client/src/components/MatPickersList.tsx
  client/src/images/Rhino.jpeg
  client/src/pages/Domain.tsx
  client/src/pages/MatPicker.tsx
  client/src/pages/MyPage.tsx
  client/src/utils/API.ts
  client/src/utils/useAxios.ts
Labels: feat, FE

#15 #8 - feat : domain 페이지 및 Post 관련 Modal과 Comment 기능 구현
  client/data.json
  client/fake_server/matData.json
  client/package-lock.json
  client/package.json
  client/src/components/MatPostModal/MatPostComment.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/PostRead.tsx
  client/src/pages/Domain.tsx
  client/src/utils/API.ts
  client/src/utils/useCommentsAxios.ts
  client/src/utils/usePlacesPostsAxios.ts
  client/src/utils/usePostsAxios.ts
  matData.json
Labels: feat, FE

#17 #2 - Kakao map 검색 기능 추가
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/KakaoMap.tsx
  client/src/components/KakaoMap/KakaoMap.tsx
  client/src/components/KakaoMap/MapSearchComponent.tsx
  client/src/components/index.tsx
  client/src/utils/useAxios.ts
  client/tsconfig.json
Labels: feat, FE

#13 #4 - places/posts 기능 풀 리퀘스트 요청합니다.
  server/matp/build.gradle
  server/matp/src/main/java/com/matp/MatpApplication.java
  server/matp/src/main/java/com/matp/comment/controller/CommentController.java
  server/matp/src/main/java/com/matp/comment/dto/CommentInfo.java
  server/matp/src/main/java/com/matp/comment/dto/CommentResponse.java
  server/matp/src/main/java/com/matp/comment/dto/CommentSpecificInfo.java
  server/matp/src/main/java/com/matp/comment/dto/MultiResponseDto.java
  server/matp/src/main/java/com/matp/comment/dto/PostCommentRequest.java
  server/matp/src/main/java/com/matp/comment/entity/Comment.java
  server/matp/src/main/java/com/matp/comment/repository/CommentRepository.java
  server/matp/src/main/java/com/matp/comment/service/CommentService.java
  server/matp/src/main/java/com/matp/exception/CustomErrorCode.java
  server/matp/src/main/java/com/matp/exception/CustomErrorResponse.java
  server/matp/src/main/java/com/matp/exception/PostNotFoundException.java
  server/matp/src/main/java/com/matp/exception/RestExceptionHandler.java
  server/matp/src/main/java/com/matp/post/config/R2dbcConfig.java
  server/matp/src/main/java/com/matp/post/controller/PostController.java
  server/matp/src/main/java/com/matp/post/dto/PatchPostRequest.java
  server/matp/src/main/java/com/matp/post/dto/PostMemberSpecificInfo.java
  server/matp/src/main/java/com/matp/post/dto/PostRequest.java
  server/matp/src/main/java/com/matp/post/dto/PostResponse.java
  server/matp/src/main/java/com/matp/post/dto/PostResponseWithInfo.java
  server/matp/src/main/java/com/matp/post/dto/testdto/PostMemberInfo.java
  server/matp/src/main/java/com/matp/post/entity/Post.java
  server/matp/src/main/java/com/matp/post/entity/testentity/TestMember.java
  server/matp/src/main/java/com/matp/post/repository/PostRepository.java
  server/matp/src/main/java/com/matp/post/service/PostService.java
Labels: feat, BE

#20 #7 - feat : modal portal 컴포넌트 추가 및 기능 구현
  client/public/index.html
  client/src/components/MatPickerModal/MatPickerCreate.tsx
  client/src/components/MatPickerModal/MatPickerDelete.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/MatPickersList.tsx
  client/src/components/ModalPortal.tsx
  client/src/components/index.tsx
  client/src/pages/MatPicker.tsx
Labels: feat, FE

#19 #14 comment 수정, 삭제, 조회 기능 풀 리퀘스트 요청합니다 Posts/comments
  server/matp/src/main/java/com/matp/comment/controller/CommentController.java
  server/matp/src/main/java/com/matp/comment/dto/CommentRequest.java
  server/matp/src/main/java/com/matp/comment/dto/CommentSpecificInfo.java
  server/matp/src/main/java/com/matp/comment/entity/Comment.java
  server/matp/src/main/java/com/matp/comment/repository/CommentRepository.java
  server/matp/src/main/java/com/matp/comment/service/CommentService.java
  server/matp/src/main/java/com/matp/post/repository/PostRepository.java
Labels: feat, BE

#23 #8 #22- feat : post modal에 PortalModal 적용( backdrop 이슈 해결을 위함) 및 Post 작성을 위한 react-quill(텍스트 에디터) import 관련 PR 요청합니다.
  client/fake_server/matData.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/MatPostModal/MatEditor.tsx
  client/src/components/MatPostModal/MatPostComment.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MatPostModal/type.d.ts
  client/src/components/PostRead.tsx
  client/src/pages/Domain.tsx
  client/src/utils/API.ts
  client/src/utils/useCommentsAxios.ts
  client/src/utils/usePlacesPostsAxios.ts
  client/src/utils/usePostsAxios.ts
Labels: feat, FE

#28 Kakao map 마커 찍기 및 상태 관리
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/KakaoMap/HoldSearchComponent/KakaoMap.tsx
  client/src/components/KakaoMap/HoldSearchComponent/MapSearchComponent.tsx
  client/src/components/KakaoMap/KakaoMap.tsx
  client/src/components/KakaoMap/MapMarkerComponent.tsx
  client/src/components/index.tsx
  client/src/store/searchAtoms.ts
  client/src/utils/usePlaceSearch.ts
Labels: feat, refactor, FE

#29 #7 - refactor : 맛픽커즈 CRUD 관련 Axios 코드 분리
  client/src/components/MatPickerModal/MatPickerCreate.tsx
  client/src/components/MatPickerModal/MatPickerDelete.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/pages/MatPicker.tsx
  client/src/pages/MatPickerDetail.tsx
  client/src/utils/usePickersAxios.ts
Labels: refactor, FE

#30 맛포스트 modal CRUD 기능 구현 관련 PR 요청합니다.
  client/src/App.tsx
  client/src/components/MatPostModal/MatEditor.tsx
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
  client/src/components/MatPostModal/StarRate.tsx
  client/src/utils/API.ts
  client/src/utils/usePlacesPostsAxios.ts
Labels: feat, FE

#32 맛포스트 modal code refactor 관련 PR 요청합니다.
  client/fake_server/matData.json
  client/src/components/MatPostModal/MatEditor.tsx
Labels: refactor, FE

#36 #25 - feat : search page 와이어프레임 및 관련 메뉴 구현
  .DS_Store
  client/src/App.tsx
  client/src/components/PeopleSearchResult.tsx
  client/src/components/index.tsx
  client/src/pages/MatPlacePick.tsx
  client/src/pages/MatPlacePost.tsx
  client/src/pages/SearchDetailPage.tsx
  client/src/pages/SearchPage.tsx
  client/src/pages/index.tsx
  matData.json
Labels: feat, FE

#37 맛피플 페이지 관련 PR 입니다.
  client/fake_server/matData.json
  client/src/App.tsx
  client/src/components/MatPeoplePickersList.tsx
  client/src/pages/MatPeople.tsx
  client/src/pages/MatPeoplePicker.tsx
  client/src/utils/usePeopleAxios.ts
Labels: feat, FE

#38 Header/login 로그인 모달 제작 및 구현
  client/src/components/Header.tsx
  client/src/components/LoginModal.tsx
  client/src/images/googleLogo.svg
  client/src/images/kakaoLogo.svg
  client/src/images/naverLogo.svg
  client/src/pages/MyPage.tsx
Labels: feat, style, FE

#27 #24 - Posts/likes 기능 풀 리퀘스트 입니다
  server/matp/src/main/java/com/matp/comment/dto/CommentRequest.java
  server/matp/src/main/java/com/matp/comment/dto/CommentResponse.java
  server/matp/src/main/java/com/matp/comment/entity/Comment.java
  server/matp/src/main/java/com/matp/comment/repository/CommentRepository.java
  server/matp/src/main/java/com/matp/comment/service/CommentService.java
  server/matp/src/main/java/com/matp/likes/controller/LikesController.java
  server/matp/src/main/java/com/matp/likes/dto/LikesRequest.java
  server/matp/src/main/java/com/matp/likes/entity/Likes.java
  server/matp/src/main/java/com/matp/likes/repository/LikesRepository.java
  server/matp/src/main/java/com/matp/likes/service/LikesService.java
  server/matp/src/main/java/com/matp/post/dto/PatchPostRequest.java
  server/matp/src/main/java/com/matp/post/dto/PostRequest.java
  server/matp/src/main/java/com/matp/post/entity/Post.java
  server/matp/src/main/java/com/matp/post/repository/PostRepository.java
  server/matp/src/main/java/com/matp/post/service/PostService.java
Labels: feat, BE

#40 #39 - feat : Matplace page 와이어프레임 및 메뉴 구현
  .gitignore
  client/fake_server/matData.json
  client/src/App.tsx
  client/src/pages/MatPlace.tsx
  client/src/pages/index.tsx
  client/src/utils/usePlacesAxios.ts
Labels: feat, FE

#46 post 이미지 핸들링 및 thumnail URL 추출 로직 추가 관련 PR 입니다.
  client/fake_server/matData.json
  client/src/components/MatPostModal/MatEditor.tsx
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
  client/src/utils/API.ts
Labels: feat, FE

#48 맛포스트 등록 및 수정 별점 관련 수정사항 PR 입니다.
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
Labels: feat, FE

#52 #50 - refactor : modal handler 코드 통일 및 정리
  client/src/App.tsx
  client/src/components/DeleteModal.tsx
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
  client/src/components/PeopleEditModal.tsx
  client/src/components/PostRead.tsx
  client/src/pages/MatPlace.tsx
  client/src/pages/MyPage.tsx
Labels: refactor, FE

#53 #34 - S3 파일업로드 기능 구현 및 ERD 설계도의 Column 이름 수정에 따른 자잘한 변경
  server/matp/.gitignore
  server/matp/build.gradle
  server/matp/src/main/java/com/matp/comment/controller/CommentController.java
  server/matp/src/main/java/com/matp/comment/dto/CommentResponse.java
  server/matp/src/main/java/com/matp/comment/dto/CommentSpecificInfo.java
  server/matp/src/main/java/com/matp/comment/dto/MultiResponseDto.java
  server/matp/src/main/java/com/matp/comment/entity/Comment.java
  server/matp/src/main/java/com/matp/comment/repository/CommentRepository.java
  server/matp/src/main/java/com/matp/comment/service/CommentService.java
  server/matp/src/main/java/com/matp/exception/CustomErrorCode.java
  server/matp/src/main/java/com/matp/exception/CustomErrorResponse.java
  server/matp/src/main/java/com/matp/exception/RestExceptionHandler.java
  server/matp/src/main/java/com/matp/likes/controller/LikesController.java
  server/matp/src/main/java/com/matp/likes/entity/Likes.java
  server/matp/src/main/java/com/matp/likes/repository/LikesRepository.java
  server/matp/src/main/java/com/matp/post/controller/PostController.java
  server/matp/src/main/java/com/matp/post/dto/PostMemberSpecificInfo.java
  server/matp/src/main/java/com/matp/post/dto/testdto/PostMemberInfo.java
  server/matp/src/main/java/com/matp/post/entity/Post.java
  server/matp/src/main/java/com/matp/post/exception/NoImageException.java
  server/matp/src/main/java/com/matp/post/exception/PostNotFoundException.java
  server/matp/src/main/java/com/matp/post/exception/UploadFailedException.java
  server/matp/src/main/java/com/matp/post/repository/PostRepository.java
  server/matp/src/main/java/com/matp/post/service/PostService.java
  server/matp/src/main/java/com/matp/s3upload/config/AwsConfig.java
  server/matp/src/main/java/com/matp/s3upload/controller/AwsS3Controller.java
  server/matp/src/main/java/com/matp/s3upload/dto/FileResponse.java
  server/matp/src/main/java/com/matp/s3upload/dto/SuccessResponse.java
  server/matp/src/main/java/com/matp/s3upload/entity/UploadStatus.java
  server/matp/src/main/java/com/matp/s3upload/exception/FileValidatorException.java
  server/matp/src/main/java/com/matp/s3upload/exception/UploadException.java
  server/matp/src/main/java/com/matp/s3upload/service/AwsS3FileStorageService.java
  server/matp/src/main/java/com/matp/s3upload/utils/AwsProperties.java
  server/matp/src/main/java/com/matp/s3upload/utils/AwsSdkUtil.java
  server/matp/src/main/java/com/matp/s3upload/utils/FileUtils.java
Labels: feat, BE

#62 맛 포스트 modal CRUD code refactor 관련 PR 입니다.
  client/fake_server/matData.json
  client/src/components/MatPickerModal/MatPickerCreate.tsx
  client/src/components/MatPickerModal/MatPickerDelete.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/MatPostModal/MatComment.tsx
  client/src/components/MatPostModal/MatCommentAdd.tsx
  client/src/components/MatPostModal/MatCommentList.tsx
  client/src/components/MatPostModal/MatEditor.tsx
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
  client/src/components/PostRead.tsx
  client/src/pages/Domain.tsx
  client/src/pages/MatPeople.tsx
  client/src/pages/MatPeoplePicker.tsx
  client/src/pages/MatPicker.tsx
  client/src/pages/MatPickerDetail.tsx
  client/src/pages/MatPlace.tsx
  client/src/utils/axiosAPI/comments/(임시)CommentHook.ts
  client/src/utils/axiosAPI/comments/commentsAxios.ts
  client/src/utils/axiosAPI/groups/(임시)PickersAxios.ts
  client/src/utils/axiosAPI/members/(임시)MatPeopleHook.ts
  client/src/utils/axiosAPI/people/PeopleAxios.ts
  client/src/utils/axiosAPI/posts/(임시)PlacesPostsHook.ts
  client/src/utils/axiosAPI/posts/(임시)PostsHook.ts
  client/src/utils/axiosAPI/posts/PlacesPostsAxios.ts
  client/src/utils/axiosAPI/posts/PostsAxios.ts
  client/src/utils/useAxios.ts
Labels: feat, refactor, FE

#63 #51 - feat : pickers & placesDetail useAxios 적용
  client/fake_server/matData.json
  client/src/components/MatPickerModal/MatPickerCreate.tsx
  client/src/components/MatPickerModal/MatPickerDelete.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/MatPickersItem.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/index.tsx
  client/src/pages/MatPeoplePicker.tsx
  client/src/pages/MatPicker.tsx
  client/src/pages/MatPickerDetail.tsx
  client/src/pages/MatPlace.tsx
  client/src/utils/axiosAPI/groups/(임시)PickersAxios.ts
  client/src/utils/axiosAPI/groups/PickersAxios.ts
  client/src/utils/axiosAPI/groups/PickersHook.ts
  client/src/utils/axiosAPI/places/PlacesAxios.ts
Labels: refactor, FE

#59 Feature/user
  server/matp/build.gradle
  server/matp/src/main/java/com/matp/auth/config/SecurityConfig.java
  server/matp/src/main/java/com/matp/auth/dto/GoogleOAuth2Response.java
  server/matp/src/main/java/com/matp/auth/dto/KakaoOAuth2Response.java
  server/matp/src/main/java/com/matp/auth/dto/MemberPrincipal.java
  server/matp/src/main/java/com/matp/auth/handler/OAuthSuccessHandler.java
  server/matp/src/main/java/com/matp/auth/jwt/JwtAuthenticationFilter.java
  server/matp/src/main/java/com/matp/auth/jwt/JwtTokenProvider.java
  server/matp/src/main/java/com/matp/follow/controller/FollowController.java
  server/matp/src/main/java/com/matp/follow/dto/FollowResponseWithInfo.java
  server/matp/src/main/java/com/matp/follow/entity/Follow.java
  server/matp/src/main/java/com/matp/follow/repository/FollowRepository.java
  server/matp/src/main/java/com/matp/follow/service/FollowService.java
  server/matp/src/main/java/com/matp/member/controller/MemberController.java
  server/matp/src/main/java/com/matp/member/dto/MemberDto.java
  server/matp/src/main/java/com/matp/member/dto/MemberPatchDto.java
  server/matp/src/main/java/com/matp/member/dto/MemberResponse.java
  server/matp/src/main/java/com/matp/member/dto/MemberSearchResponse.java
  server/matp/src/main/java/com/matp/member/entity/Member.java
  server/matp/src/main/java/com/matp/member/repository/MemberCustomRepository.java
  server/matp/src/main/java/com/matp/member/repository/MemberRepository.java
  server/matp/src/main/java/com/matp/member/service/MemberService.java
  server/matp/src/main/java/com/matp/post/dto/SimplePostResponse.java
Labels: feat, BE

#43 #21 - 주변 플레이스 조회
  server/matp/src/main/java/com/matp/place/controller/PlaceController.java
  server/matp/src/main/java/com/matp/place/dto/PlaceDetailResponseDto.java
  server/matp/src/main/java/com/matp/place/dto/PlaceResponseDto.java
  server/matp/src/main/java/com/matp/place/entity/Place.java
  server/matp/src/main/java/com/matp/place/repository/PlaceRepositiory.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
  server/matp/src/main/java/com/matp/post/dto/PlaceDetailPostDto.java
  server/matp/src/main/java/com/matp/post/repository/PostRepository.java
  server/matp/src/main/java/com/matp/post/service/PostService.java
Labels: feat, BE

#54 #47 - 피커 CRUD 기능
  server/matp/src/main/java/com/matp/group/controller/GroupController.java
  server/matp/src/main/java/com/matp/group/dto/GroupRequestDto.java
  server/matp/src/main/java/com/matp/group/dto/GroupResponseDto.java
  server/matp/src/main/java/com/matp/group/entity/Group.java
  server/matp/src/main/java/com/matp/group/repository/GroupRepository.java
  server/matp/src/main/java/com/matp/group/service/GroupService.java
Labels: feat, BE

#56 #55 - Place Picker 픽 요청/취소
  server/matp/src/main/java/com/matp/picker/controller/PickerController.java
  server/matp/src/main/java/com/matp/picker/dto/PickerResponseDto.java
  server/matp/src/main/java/com/matp/picker/entity/Picker.java
  server/matp/src/main/java/com/matp/picker/repository/PickerRepository.java
  server/matp/src/main/java/com/matp/picker/service/PickerService.java
Labels: feat, BE

#64 플레이스 조회시 마커 유무 체크 매핑 / 검색
  server/matp/src/main/java/com/matp/place/controller/PlaceController.java
  server/matp/src/main/java/com/matp/place/dto/PlaceDetailResponseDto.java
  server/matp/src/main/java/com/matp/place/repository/PlaceRepositiory.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
Labels: feat, BE

#72 #4 최종 업데이트 전 코드 병합
  server/matp/build.gradle
  server/matp/src/main/java/com/matp/comment/dto/CommentInfo.java
  server/matp/src/main/java/com/matp/comment/entity/Comment.java
  server/matp/src/main/java/com/matp/comment/repository/CommentRepository.java
  server/matp/src/main/java/com/matp/comment/service/CommentService.java
  server/matp/src/main/java/com/matp/place/controller/PlaceController.java
  server/matp/src/main/java/com/matp/place/dto/PlaceEnrollmentRequest.java
  server/matp/src/main/java/com/matp/place/dto/PlaceEnrollmentResponse.java
  server/matp/src/main/java/com/matp/place/repository/PlaceRepositiory.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
  server/matp/src/main/java/com/matp/post/controller/PostController.java
  server/matp/src/main/java/com/matp/post/dto/PostMemberInfo.java
  server/matp/src/main/java/com/matp/post/dto/PostMemberSpecificInfo.java
  server/matp/src/main/java/com/matp/post/dto/PostResponse.java
  server/matp/src/main/java/com/matp/post/dto/PostResponseWithInfo.java
  server/matp/src/main/java/com/matp/post/entity/Post.java
  server/matp/src/main/java/com/matp/post/entity/testentity/TestMember.java
  server/matp/src/main/java/com/matp/post/repository/PostRepository.java
  server/matp/src/main/java/com/matp/post/service/PostService.java
Labels: feat, BE

#73 리팩토링 - (유저) 피드백 수용 후 코드 변경 사항 적용
  server/matp/src/main/java/com/matp/auth/config/SecurityConfig.java
  server/matp/src/main/java/com/matp/auth/config/WebConfig.java
  server/matp/src/main/java/com/matp/auth/dto/GoogleOAuth2Response.java
  server/matp/src/main/java/com/matp/auth/dto/KakaoOAuth2Response.java
  server/matp/src/main/java/com/matp/auth/dto/MemberPrincipal.java
  server/matp/src/main/java/com/matp/auth/handler/OAuthSuccessHandler.java
  server/matp/src/main/java/com/matp/auth/jwt/JwtAuthenticationFilter.java
  server/matp/src/main/java/com/matp/auth/jwt/JwtTokenProvider.java
  server/matp/src/main/java/com/matp/follow/controller/FollowController.java
  server/matp/src/main/java/com/matp/follow/entity/Follow.java
  server/matp/src/main/java/com/matp/follow/repository/FollowRepository.java
  server/matp/src/main/java/com/matp/follow/service/FollowService.java
  server/matp/src/main/java/com/matp/member/controller/MemberController.java
  server/matp/src/main/java/com/matp/member/dto/MemberDto.java
  server/matp/src/main/java/com/matp/member/dto/MemberResponse.java
  server/matp/src/main/java/com/matp/member/entity/Member.java
  server/matp/src/main/java/com/matp/member/repository/MemberCustomRepository.java
  server/matp/src/main/java/com/matp/member/repository/MemberRepository.java
  server/matp/src/main/java/com/matp/member/service/MemberService.java
Labels: feat, refactor, BE

#66 마이페이지 프로필 이미지 변경 기능 관련 PR 입니다.
  client/src/pages/MyPage.tsx
  client/tsconfig.json
Labels: feat, FE

#67 맛포스트 모달 useAxios 실시간 업데이트 관련 수정 사항 PR입니다.
  client/src/components/MatPostModal/MatCommentAdd.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
Labels: refactor, FE

#68 #50 - refactor : post modal handler 코드 통일 및 정리
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
  client/src/pages/MatPlace.tsx
Labels: refactor, FE

#70 #69 - feat :맛픽커즈 고유 이미지 연결
  client/src/components/MatPeoplePickersItem.tsx
  client/src/components/MatPickerModal/MatPickerCreate.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/MatPickersItem.tsx
  client/src/pages/MatPeoplePicker.tsx
  client/src/pages/MatPickerDetail.tsx
Labels: feat, FE

#74 맛플레이스 페이지 별점 평균 및 별점 종합 차트 관련 PR입니다.
  client/src/pages/MatPlace.tsx
Labels: feat, FE

#75 #71 - refactor : KakaoOAuth2Response 수정
  server/matp/src/main/java/com/matp/auth/dto/KakaoOAuth2Response.java
Labels: fix, refactor

#76 #4 최종 배포 전 테스트 배포를 위한 코드 병합 풀 리퀘스트 입니다
  server/matp/src/main/java/com/matp/MatpApplication.java
  server/matp/src/main/java/com/matp/auth/config/WebConfig.java
  server/matp/src/main/java/com/matp/auth/handler/OAuthSuccessHandler.java
  server/matp/src/main/java/com/matp/comment/controller/CommentController.java
  server/matp/src/main/java/com/matp/comment/service/CommentService.java
  server/matp/src/main/java/com/matp/exception/CustomErrorCode.java
  server/matp/src/main/java/com/matp/exception/CustomErrorResponse.java
  server/matp/src/main/java/com/matp/exception/CustomException.java
  server/matp/src/main/java/com/matp/exception/RestExceptionHandler.java
  server/matp/src/main/java/com/matp/likes/controller/LikesController.java
  server/matp/src/main/java/com/matp/member/dto/MemberResponse.java
  server/matp/src/main/java/com/matp/member/entity/Member.java
  server/matp/src/main/java/com/matp/member/repository/MemberCustomRepository.java
  server/matp/src/main/java/com/matp/member/service/MemberService.java
  server/matp/src/main/java/com/matp/place/repository/PlaceRepositiory.java
  server/matp/src/main/java/com/matp/post/controller/PostController.java
  server/matp/src/main/java/com/matp/post/exception/PostNotFoundException.java
  server/matp/src/main/java/com/matp/post/service/PostService.java
  server/matp/src/main/resources/application.yml
Labels: fix, feat, refactor, BE

#77 #25 -feat: 맛플레이스 추가 요청 페이지 구현
  client/fake_server/matData.json
  client/src/App.tsx
  client/src/components/MatPeoplePickersItem.tsx
  client/src/components/MatPickerModal/MatPickerCreate.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/MatPickersItem.tsx
  client/src/pages/MatPicker.tsx
  client/src/pages/MatPlace.tsx
  client/src/pages/MatPlacePostPage.tsx
  client/src/pages/SearchDetailPage/SearchDetailPlace.tsx
  client/src/pages/index.tsx
  client/src/utils/axiosAPI/places/PlacesAxios.ts
Labels: feat, FE

#78 맛포스트 모달 '맛플레이스로 이동하기' 버튼 추가 및 Delete Confirm 기능 구현 관련 PR입니다.
  client/fake_server/matData.json
  client/package-lock.json
  client/package.json
  client/src/components/MatPostModal/MatComment.tsx
  client/src/components/MatPostModal/MatCommentList.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/PostRead.tsx
  client/src/pages/Domain.tsx
  client/src/pages/SearchDetailPage/SearchDetailPost.tsx
  client/src/utils/axiosAPI/comments/commentsAxios.ts
  client/src/utils/axiosAPI/posts/PostsAxios.ts
Labels: feat, FE

#79 Page/my page 팔로잉, 팔로워 리스트 구현 및 update후 바로 반영 기능들 추가
  client/fake_server/matData.json
  client/src/pages/MyPage.tsx
  client/src/utils/axiosAPI/members/myPageAPI.ts
Labels: feat, style, FE

#82 플레이스 조회 리팩토링
  server/matp/src/main/java/com/matp/group/service/GroupService.java
  server/matp/src/main/java/com/matp/picker/repository/PickerRepository.java
  server/matp/src/main/java/com/matp/picker/service/PickerService.java
  server/matp/src/main/java/com/matp/place/dto/PlaceDetailResponseDto.java
  server/matp/src/main/java/com/matp/place/dto/PlaceEnrollmentRequest.java
  server/matp/src/main/java/com/matp/place/dto/PlaceEnrollmentResponse.java
  server/matp/src/main/java/com/matp/place/entity/Place.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
Labels: feat, refactor, BE

#81 맛포스트 모달 시간 변환 리팩토링 관련 PR입니다.
  client/fake_server/matData.json
  client/package-lock.json
  client/package.json
  client/src/api/axiosAPI/posts/PostsAxios.ts
  client/src/components/MatPostModal/MatComment.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
Labels: refactor, FE

#84 #83 -feat: not found 페이지 구성
  client/package-lock.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/pages/NotFoundPage.tsx
  client/src/pages/index.tsx
Labels: feat, FE

#86 피커 리팩토링
  server/matp/src/main/java/com/matp/picker/controller/PickerController.java
  server/matp/src/main/java/com/matp/picker/dto/PickerRequestDto.java
  server/matp/src/main/java/com/matp/picker/dto/PickerResponseDto.java
  server/matp/src/main/java/com/matp/picker/entity/Picker.java
  server/matp/src/main/java/com/matp/picker/repository/PickerRepository.java
  server/matp/src/main/java/com/matp/picker/service/PickerService.java
  server/matp/src/main/java/com/matp/place/dto/PlaceDetailResponseDto.java
  server/matp/src/main/java/com/matp/place/repository/PlaceRepository.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
Labels: feat, refactor, BE

#88 피커 jwt 토큰 및 검증 추가
  server/matp/src/main/java/com/matp/exception/CustomErrorCode.java
  server/matp/src/main/java/com/matp/picker/controller/PickerController.java
  server/matp/src/main/java/com/matp/picker/service/PickerService.java
Labels: feat, refactor, BE

#90 플레이스 jwt 토큰 추가
  server/matp/src/main/java/com/matp/place/controller/PlaceController.java
Labels: refactor, BE

#92 플레이스 조회 리팩토링
  server/matp/src/main/java/com/matp/place/dto/PlaceDetailResponseDto.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
Labels: fix, feat, refactor, BE

#94 matPost modal & matPeople page & pickers & places 서버 연결 관련 PR입니다.
  client/package-lock.json
  client/src/App.tsx
  client/src/api/axiosAPI/comments/commentsAxios.ts
  client/src/api/axiosAPI/groups/PickersAxios.ts
  client/src/api/axiosAPI/members/myPageAPI.ts
  client/src/api/axiosAPI/people/PeopleAxios.ts
  client/src/api/axiosAPI/places/PlacesAxios.ts
  client/src/api/axiosAPI/posts/PostsAxios.ts
  client/src/components/MatPeoplePickersItem.tsx
  client/src/components/MatPickersItem.tsx
  client/src/components/MatPostModal/MatComment.tsx
  client/src/components/MatPostModal/MatCommentAdd.tsx
  client/src/components/MatPostModal/MatCommentList.tsx
  client/src/components/MatPostModal/MatEditor.tsx
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MatPostModal/MatPostUpdate.tsx
  client/src/components/PostRead.tsx
  client/src/hooks/useAxios.ts
  client/src/index.tsx
  client/src/pages/DomainPage.tsx
  client/src/pages/MatPeoplePage.tsx
  client/src/pages/MatPeoplePickerPage.tsx
  client/src/pages/MatPickerDetailPage.tsx
  client/src/pages/MatPlacePage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SearchDetailPage/SearchDetailPost.tsx
Labels: feat, refactor, FE

#96 #57 - feat : 유저 검색 페이지네이션 추가
  server/matp/src/main/java/com/matp/member/controller/MemberController.java
Labels: feat, BE

#97 플레이스 검색 페이지네이션
  server/matp/src/main/java/com/matp/place/controller/PlaceController.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
Labels: feat, BE

#99 픽한 플레이스 전체 조회
  server/matp/src/main/java/com/matp/group/repository/GroupRepository.java
  server/matp/src/main/java/com/matp/picker/controller/PickerController.java
  server/matp/src/main/java/com/matp/picker/service/PickerService.java
  server/matp/src/main/java/com/matp/place/dto/PlaceResponseDto.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
Labels: feat, refactor, BE

#95 서버 연결 관련 관련 PR입니다.
  client/src/api/CustomAxios.ts
  client/src/api/axiosAPI/comments/commentsAxios.ts
  client/src/api/axiosAPI/groups/PickersAxios.ts
  client/src/api/axiosAPI/members/myPageAPI.ts
  client/src/api/axiosAPI/people/PeopleAxios.ts
  client/src/api/axiosAPI/places/PlacesAxios.ts
  client/src/api/axiosAPI/posts/PostsAxios.ts
  client/src/api/axiosAPI/search/PeopleSearchAxios.ts
  client/src/api/axiosAPI/search/placeSearchAxios.ts
  client/src/api/axiosAPI/search/postSearchAxios.ts
  client/src/components/MatPickerModal/MatPickerCreate.tsx
  client/src/components/MatPickerModal/MatPickerDelete.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/MatPickersItem.tsx
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/PeopleSearchResult.tsx
  client/src/components/PlaceSearchResult.tsx
  client/src/pages/MatPeoplePage.tsx
  client/src/pages/MatPickerPage.tsx
  client/src/pages/MatPlacePage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SearchDetailPage/SearchDetailPeople.tsx
  client/src/pages/SearchDetailPage/SearchDetailPlace.tsx
  client/src/pages/SearchDetailPage/SearchDetailPost.tsx
Labels: feat, style, FE

#100 도메인 페이지 무한스크롤 구현 및 로그인 시 마커 찍기 구현
  client/src/App.tsx
  client/src/api/axiosAPI/groups/PickersAxios.ts
  client/src/api/axiosAPI/posts/PostsAxios.ts
  client/src/components/KakaoMap/HoldSearchComponent/KakaoMap.tsx
  client/src/components/KakaoMap/HoldSearchComponent/MapSearchComponent.tsx
  client/src/components/KakaoMap/KakaoMap.tsx
  client/src/components/KakaoMap/MapMarkerComponent.tsx
  client/src/components/KakaoMap/PIckerMarker.tsx
  client/src/components/KakaoMap/PlaceDetailMarker.tsx
  client/src/components/KakaoMap/SearchMarker.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/PlaceSearchResult.tsx
  client/src/components/Sidebar.tsx
  client/src/hooks/useAxios.ts
  client/src/pages/DomainPage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/MatPickerDetailPage.tsx
  client/src/pages/MatPlacePage.tsx
  client/src/pages/MatPlacePostPage.tsx
  client/src/pages/SearchDetailPage/SearchDetailPlace.tsx
  client/src/pages/index.tsx
  client/src/store/placeInfoAtoms.ts
  client/src/store/searchPlaceAtoms.ts
Labels: feat, FE

#101 #80 -feat: modal backdrop 클로즈 기능 보수
  client/src/pages/LoginPage.tsx
  client/src/pages/MatPeoplePage.tsx
  client/src/pages/MatPickerDetailPage.tsx
  client/src/pages/MatPlacePage.tsx
Labels: feat, FE

#104 다른 유저 픽 조회
  server/matp/src/main/java/com/matp/picker/controller/PickerController.java
  server/matp/src/main/java/com/matp/picker/service/PickerService.java
Labels: refactor, BE

#105 Infinify scroll 다른 컴포넌트에 구현 및 모달 디자인 통일
  client/src/api/axiosAPI/posts/PostsAxios.ts
  client/src/components/Header.tsx
  client/src/components/KakaoMap/PIckerMarker.tsx
  client/src/components/LogoutModal.tsx
  client/src/components/MatPickerModal/MatPickerDelete.tsx
  client/src/components/MatPickerModal/MatPickerUpdate.tsx
  client/src/components/MatPickersItem.tsx
  client/src/components/MatPostModal/MatEditor.tsx
  client/src/components/MatPostModal/MatPostCreate.tsx
  client/src/components/MatPostModal/MatPostRead.tsx
  client/src/components/MyPagePostInfo.tsx
  client/src/components/PostRead.tsx
  client/src/pages/DomainPage.tsx
  client/src/pages/MatPeoplePage.tsx
  client/src/pages/MatPlacePage.tsx
  client/src/pages/MyPage.tsx
Labels: feat, style, refactor, FE

#107 검색시 평점, 그룹 매핑 제외
  server/matp/src/main/java/com/matp/place/controller/PlaceController.java
  server/matp/src/main/java/com/matp/place/dto/PlaceSearchResponseDto.java
  server/matp/src/main/java/com/matp/place/service/PlaceService.java
Labels: refactor, BE
